### ISSUE TITLE
PUL03 | Display band profile

### ISSUE THREAD

**Issue by glixius** [glixius/pulsar-web-client#8]
### Description
Once users get authenticated, they should be redirected to band profile. Band profile will show general information and registered songs. 

### Tasks
- [ ] Create band profile view.
- [ ] Add Band service.
- [ ] Add no songs and error messages.
- [ ] Add role management to user data.
- [ ] Apply role specific functionality.
